Models/Stock.cs
namespace TechLife.Models
{
    public class Stock
    {
        public int Id { get; set; }
        public int ShopStoreId { get; set; }
        public int Quantity { get; set; }
        public int? SupplierItemId { get; set; }
        public ShopStore? ShopStore { get; set; }
        public SupplierItem? SupplierItem { get; set; }
    }

}

Areas/Admin/Controllers/StockController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TechLife.Models.DTOs;
using TechLife.Repository;

namespace TechLife.Areas.Admin.Controllers
{
    [Area("Admin")]

    [Authorize(Roles = SD.Role_Admin)]
    public class StockController : Controller
    {
        private readonly IStockRepository _stockRepo;

        public StockController(IStockRepository stockRepo)
        {
            _stockRepo = stockRepo;
        }

        public async Task<IActionResult> Index(string sTerm = "")
        {
            var stocks = await _stockRepo.GetStocks(sTerm);
            return View(stocks);
        }

        public async Task<IActionResult> ManageStock(int shopStoreId)
        {
            var existingStock = await _stockRepo.GetStockByBookId(shopStoreId);
            var stock = new StockDTO
            {
                ShopStoreId = shopStoreId,
                Quantity = existingStock != null
            ? existingStock.Quantity : 0
            };
            return View(stock);
        }

        [HttpPost]
        public async Task<IActionResult> ManageStock(StockDTO stock)
        {
            if (!ModelState.IsValid)
                return View(stock);
            try
            {
                await _stockRepo.ManageStock(stock);
                TempData["successMessage"] = "Stock is updated successfully.";
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = "Something went wrong!!";
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

Areas/Admin/Views/Stock/Index.cshtml
@using TechLife.Models.DTOs
@model IEnumerable<StockDisplayModel>

@{
    Layout = "_AdminLayout";
}
<h2>Stocks</h2>

<form asp-action="Index" method="get" class="my-2 d-flex gap-2">
    <input type="text" name="sTerm" class="form-control w-25" placeholder="Search by Item" />
    <button type="submit" class="btn btn-primary">Find</button>
    <a asp-action="Index" asp-controller="Stock" class="btn btn-primary">Clear</a>
</form>

<table class="table table-bordered">
    <tr>
        <th>Item</th>
        <th>Stock</th>
        <th>Actions</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.ShopeStoreName</td>
            <td>@item.Quantity</td>
            <td>
                <a asp-area="Admin" asp-action="ManageStock" asp-controller="Stock" asp-route-shopStoreId="@item.ShopStoreId" class="btn btn-info"> Update Stock</a>
            </td>
        </tr>
    }
</table>

Areas/Admin/Views/Stock/ManageStock.cshtml
@using TechLife.Models.DTOs
@model StockDTO
@{
    Layout = "_AdminLayout";
}

<div style="width:50%">
    <h2> Manage Stock </h2>
    <a asp-action="Index" asp-controller="Stock" class="btn btn-primary">Back</a>
    <form asp-action="ManageStock">
        <input type="hidden" asp-for="ShopStoreId" />

        <div class="my-2">
            <label>Quantity</label>
            <input type="number" class="form-control" asp-for="Quantity" />
            <span asp-validation-for="Quantity" class="text-danger"></span>
        </div>

        <div class="my-2">
            <button type="submit" class="btn btn-info">Update</button>
        </div>
    </form>
</div>